### ISSUE TITLE
DLL Hijacking clarification

### ISSUE THREAD

**Issue by hxnoyd** [Cyb3r-Monk/Threat-Hunting-and-Detection#2]
On DLL Hijacking - HijackLibs.md you extend DLLDir from tolower(InitiatingProcessFileName).

I was expecting it to be something like tolower(FolderPath). Am I missing something?

Thanks in advance!

**Comment by Cyb3r-Monk** [comment]
I've no idea how that happened but the query was working as expected with some tests. It's fixed now. Thanks for the heads up!
