### ISSUE TITLE
New Expected Path

### ISSUE THREAD

**Issue by mulder1** [Cyb3r-Monk/Threat-Hunting-and-Detection#4]
Hello, I believe this path %system32%\wbem should be added as Expected Location for both DLLs. Seem false positives:  
wbemprox.dll
wbemsvc.dll
![image](https://user-images.githubusercontent.com/23101316/200793942-f7d72427-c5da-4c84-8bc8-5bd10ecba6e7.png)

**Comment by Cyb3r-Monk** [comment]
I haven't seen this libraries loaded by msedge in my lab. Could it be something custom to the environment?

**Comment by mulder1** [comment]
It's a known alternate location for the files. And judging by the logic of the query I think the reason it's listed Suspicious is because it's location is not added to Expected locations, not because it's unusual to be loaded by Edge.
https://www.file.net/process/wbemprox.dll.html

**Comment by mulder1** [comment]
I can see Edge is one of the expected programs listed as using this libraries (andalso possible target for hijacking)
Here:
https://hijacklibs.net/entries/microsoft/built-in/wbemprox.html

**Comment by Cyb3r-Monk** [comment]
I've synced the csf file. Let me know if it doesn't work.
